server.port=8084

spring.application.name=telemetry-backend

# ---------- PostgreSQL --------------
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/mqttdb}
spring.datasource.username=${DB_USERNAME:mqtt_user}
spring.datasource.password=${DB_PASSWORD:mqtt_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

# ---------- JPA ---------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ---------- Kafka ------------------
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.kafka.consumer.group-id=telemetry-consumer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# ---------- Kafka Topics ------------
kafka.topic.telemetry-raw=vehicle-telemetry

# ---------- MQTT -------------------
mqtt.broker-url=${MQTT_BROKER_URL:ssl://localhost:8883}
mqtt.client-id=spring-backend-client
mqtt.username=${MQTT_USERNAME:mqtt}
mqtt.password=${MQTT_PASSWORD:mqttroot}
mqtt.topic-filter=devices/+/telemetry
mqtt.qos=1
# ---------- MQTT SSL -------------
mqtt.ssl.truststore=classpath:mqtt-truststore.jks
mqtt.ssl.truststore-password=changeit

# ---------- ML API ----------
ml.api.base-url=${ML_API_URL:http://localhost:8000}
ml.api.timeout-ms=5000

# ---------- Logging ----------
logging.level.com.telemetry.backend=INFO

# ---------- FrontEnd----------
app.frontend-url=${FRONTEND_URL:http://localhost:4200}