name: Frontend CI/CD

on:
  push:
    branches: [main]
    paths:
      - "telemetry-dashboard/**"
      - ".github/workflows/frontend-ci.yml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/telemetry-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image_tag: ${{ steps.meta.outputs.short_sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set short SHA
        id: meta
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .                              # ← racine du repo, pas ./telemetry-dashboard
          file: ./docker/Frontend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.short_sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-gitops:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/telemetry-gitops
          token: ${{ secrets.GITOPS_PAT }}
          path: gitops

      - name: Update image tag
        run: |
          cd gitops
          sed -i "s|image: ghcr.io/.*/telemetry-frontend:.*|image: ghcr.io/${{ github.repository_owner }}/telemetry-frontend:${{ needs.build-and-push.outputs.image_tag }}|" k8s/base/frontend-deployment.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add k8s/base/frontend-deployment.yaml
          git commit -m "chore: bump frontend image to ${{ needs.build-and-push.outputs.image_tag }}" || echo "Nothing to commit"
          git push
